=pod

B<ThisE<39>s a fork of L<btkbdd|https://github.com/lkundrak/btkbdd> authored by
L<Lubomir Rintel|https://github.com/lkundrak> that aims to send normal text
(supplied as a command-line argument) as keystrokes typed on a bluetooth
keyboard.>

=head1 btkbdd and evmuxd

This is a package that provides two nifty tools for sharing your keyboard via
Bluetooth and optionally multiplexing in a way that permits the keyboard to be
switched between local and remote use.

Please refer to L<evmuxd(8)> and L<btkbdd(8)> manuals for details about the
operation of the tools.

=begin html

<center>
<img type="image/png" src="architecture.png" alt="">
</center>

=end html

=head2 usage notes

One way to input passwords without echoing them to the terminal(assuming a bash
shell is used) is to execute:

 (read -s; btkbdd -t <target_address> "$REPLY")

=cut
